### ISSUE TITLE
Unable to add conference

### ISSUE THREAD

**Issue by shar1z** [tech-conferences/conference-data#1568] opened 2019-10-18 08:18 UTC
Hi There,
I've been attempting to add a conference via the confs.tech site - and after clicking submit nothing happens.  It thinks for a second, hangs, and then nothing happens.

Happy to submit a PR via the repo - please advise how to do so.

**Comment by nimzco** [comment] 2019-10-18 09:03
Oh weird, can you give us a bit more info? Maybe a screenshot could help us reproduce the bug.

Otherwise you can have a look at the other PRs to add the conference. Just add it in the right file and 💨

**Comment by nimzco** [comment] 2019-10-18 12:40
It might be possible that you’re trying to add an existing conference and the server doesn’t let you add it. 🤔
I’ve got to add Bugsnag and handle error better...

**Comment by XjSv** [comment] 2019-10-24 19:14
I just added 3 conferences and I did not experience any issues. 

- https://github.com/tech-conferences/conference-data/pull/1592
- https://github.com/tech-conferences/conference-data/pull/1591
- https://github.com/tech-conferences/conference-data/pull/1590

I'm using Firefox Developer Edition (v71.0b3) and I used this page to submit them: 

https://confs.tech/conferences/new

**Comment by nimzco** [comment] 2019-10-25 00:06
Since we don’t have any more information and cannot reproduce, I’ll close the issue.
Thanks!

**Closed by nimzco** 2019-10-25 00:06 UTC
